In [1]:
import pandas as pd
import numpy as np
df = pd.read_pickle('./data/batters.pkl')

In [3]:
df.head()

,Innings Player,Innings Runs Scored,Innings Runs Scored Num,Innings Minutes Batted,Innings Batted Flag,Innings Not Out Flag,Innings Balls Faced,Innings Boundary Fours,Innings Boundary Sixes,Innings Batting Strike Rate,Innings Number,50's,100's,Innings Runs Scored Buckets
0,L Hutton,364,364,797,1.0,0.0,847,35,0,42.97,1,0.0,1.0,200+
1,WR Hammond,336*,336,318,1.0,1.0,-,34,10,-,2,0.0,1.0,200+
2,GA Gooch,333,333,628,1.0,0.0,485,43,3,68.65,1,0.0,1.0,200+
3,A Sandham,325,325,600,1.0,0.0,640,28,0,50.78,1,0.0,1.0,200+
4,JH Edrich,310*,310,532,1.0,1.0,450,52,5,68.88,1,0.0,1.0,200+

# Innings Runs Scored
Possible values are
* Numeric: Runs scored
* Numeric: Runs scored appended with * for NO
* DNB: Did Not Bat
* absent: Probably retired hurt
* TDNB: ?
* sub: Substitute
* NaN: For bowler rows

**Use**: NO. *Since we're interested in stuff like scores and averages.*

In [8]:
df[(df['Innings Runs Scored'].str.isnumeric() == False) & (df['Innings Runs Scored'].str.endswith("*") == False)]['Innings Runs Scored'].unique()

array(['DNB', 'absent', 'TDNB', 'sub'], dtype=object)

# Innings Runs Scored Num
Possible values:
* Numeric: Runs scored
* \- (Dash): For `DNB`, `absent`, `TDNB`, `sub` of `Innings Runs Scored` column
* NaN: For bowler rows

**Use**: Yes. But, we're going to replace the `-` with NaN - `fillna`, maybe. Basically, we don't really care why a batter didn't bat. Just that the batter did or didn't. And replacing - with NaN allows us to dtype this as a Int / Float column. And then do number crunching (literally) on it.

In [12]:
df[(df['Innings Runs Scored Num'].str.isnumeric() == False)]['Innings Runs Scored'].unique()

array(['DNB', 'absent', 'TDNB', 'sub'], dtype=object)

# Innings Minutes Batted
Possible values:
* Numeric: Minutes
* \- (Dash): Possibly for not recorded
* NaN: For bowler rows

**Use**: Yes. Again, let's replace `-` with `NaN`. See `Innings Runs Scored Num` for explanation

In [18]:
df[df['Innings Minutes Batted'].str.isnumeric() == False]['Innings Minutes Batted'].unique()

array(['-'], dtype=object)

# Innings Batted Flag
Possible values:
* 1: Batted
* 0: Not batted. For `DNB`, `absent`, `TDNB`, `sub` of `Innings Runs Scored` column

**Use**: No. The `Innings Runs Scored Num` column should do the job. I think

In [24]:
df[(df['Innings Batted Flag'] == 0)]['Innings Runs Scored'].unique()

array(['DNB', 'absent', 'TDNB', 'sub'], dtype=object)

# Innings Not Out Flag
Possible values:
* 1: Not out
* 0: Out
* NaN: For bowler rows

**Use**: Yes.

In [31]:
df[(df['Innings Not Out Flag'].isna() == False)]['Innings Not Out Flag'].unique()

array([0., 1.])

# Innings Balls Faced
Possible values:
* Numeric: Balls faced
* \- (Dash): Possibly for not recorded
* NaN: For bowler rows

**Use**: Yes. Again, let's replace `-` with `NaN`. See `Innings Runs Scored Num` for explanation

In [32]:
df[df['Innings Balls Faced'].str.isnumeric() == False]['Innings Balls Faced'].unique()

array(['-'], dtype=object)

# Innings Boundary Fours
Possible values:
Numeric: Balls faced
•- (Dash): Possibly for not recorded
•NaN: For bowler rows

**Use**: Yes. Again, let's replace `-` with `NaN`. See `Innings Runs Scored Num` for explanation

In [16]:
df[df['Innings Boundary Fours'].str.isnumeric() == False]['Innings Boundary Fours'].unique()

array(['-'], dtype=object)

# Innings Boundary Sixes
See `Innings Boundary Fours`

In [17]:
df[df['Innings Boundary Sixes'].str.isnumeric() == False]['Innings Boundary Sixes'].unique()

array(['-'], dtype=object)

# Innings Batting Strike Rate
Possible values
* Numeric: Strike rate
* \- (Dash): Possibly for not recorded
* NaN: For bowler rows

**Use**: No. This is computed as `Innings Runs Scored Num` / `Innings Balls Faced`.
But when computing this, we need to keep in mind that `Innings Runs Scored Num` could be a Numeric. But this field is not computable if `Innings Balls Faced` is `NaN` (because it wasn't recorded). See `Innings Balls Faced`

# Innings Number
Possible values:
* 1: First innings
* 2: Second innings
* \- (Dash): If `Innings Runs Scored` = `TDNB`. And we'll replace `-` with `NaN`. For both batters anad bowlers

**Use**: Yes.

In [30]:
df[(df['Innings Number'] == '-') & (df['Innings Runs Scored'] != 'TDNB')]

Empty DataFrame
Columns: [Innings Player, Innings Runs Scored, Innings Runs Scored Num, Innings Minutes Batted, Innings Batted Flag, Innings Not Out Flag, Innings Balls Faced, Innings Boundary Fours, Innings Boundary Sixes, Innings Batting Strike Rate, Innings Number, Opposition, Ground, Innings Date, Country, 50's, 100's, Innings Runs Scored Buckets, Innings Overs Bowled, Innings Bowled Flag, Innings Maidens Bowled, Innings Runs Conceded, Innings Wickets Taken, 4 Wickets, 5 Wickets, 10 Wickets, Innings Wickets Taken Buckets, Innings Economy Rate]
Index: []

[0 rows x 28 columns]

# 50's
Possible values:
* 1: 49 < `Innings Runs Scored Num` < 100
* 0: Not a half century
* NaN: For bowler rows

**Use**: No. Computed field

In [37]:
df[(df["50's"] == 0)]

,Innings Player,Innings Runs Scored,Innings Runs Scored Num,Innings Minutes Batted,Innings Batted Flag,Innings Not Out Flag,Innings Balls Faced,Innings Boundary Fours,Innings Boundary Sixes,Innings Batting Strike Rate,Innings Number,50's,100's,Innings Runs Scored Buckets
0,L Hutton,364,364,797,1.0,0.0,847,35,0,42.97,1,0.0,1.0,200+
1,WR Hammond,336*,336,318,1.0,1.0,-,34,10,-,2,0.0,1.0,200+
2,GA Gooch,333,333,628,1.0,0.0,485,43,3,68.65,1,0.0,1.0,200+
3,A Sandham,325,325,600,1.0,0.0,640,28,0,50.78,1,0.0,1.0,200+
4,JH Edrich,310*,310,532,1.0,1.0,450,52,5,68.88,1,0.0,1.0,200+
5,AN Cook,294,294,773,1.0,0.0,545,33,0,53.94,2,0.0,1.0,200+
6,RE Foster,287,287,419,1.0,0.0,-,37,0,-,2,0.0,1.0,200+
7,PBH May,285*,285,600,1.0,1.0,-,25,2,-,3,0.0,1.0,200+
8,DCS Compton,278,278,287,1.0,0.0,-,34,1,-,2,0.0,1.0,200+
9,AN Cook,263,263,836,1.0,0.0,528,18,0,49.81,2,0.0,1.0,200+
10,DL Amiss,262*,262,570,1.0,1.0,563,40,1,46.53,3,0.0,1.0,200+
11,TW Graveney,258,258,471,1.0,0.0,-,30,0,-,1,0.0,1.0,200+
12,BA Stokes,258,258,338,1.0,0.0,198,30,11,130.30,1,0.0,1.0,200+
13,KF Barrington,256,256,683,1.0,0.0,624,26,0,41.02,2,0.0,1.0,200+
14,JE Root,254,254,614,1.0,0.0,406,27,0,62.56,1,0.0,1.0,200+
15,WR Hammond,251,251,461,1.0,0.0,605,30,0,41.48,2,0.0,1.0,200+
16,G Boycott,246*,246,573,1.0,1.0,555,30,1,44.32,1,0.0,1.0,200+
17,AN Cook,244*,244,634,1.0,1.0,409,27,0,59.65,2,0.0,1.0,200+
18,E Paynter,243,243,334,1.0,0.0,-,24,0,-,1,0.0,1.0,200+
19,AN Cook,243,243,588,1.0,0.0,407,33,0,59.70,1,0.0,1.0,200+
20,WR Hammond,240,240,367,1.0,0.0,394,32,0,60.91,1,0.0,1.0,200+
21,AN Cook,235*,235,625,1.0,1.0,428,26,0,54.90,3,0.0,1.0,200+
22,IR Bell,235,235,497,1.0,0.0,364,23,2,64.56,1,0.0,1.0,200+
23,WR Hammond,231*,231,460,1.0,1.0,579,27,0,39.89,1,0.0,1.0,200+
24,WR Hammond,227,227,301,1.0,0.0,-,-,0,-,1,0.0,1.0,200+
25,KP Pietersen,227,227,428,1.0,0.0,308,33,1,73.70,2,0.0,1.0,200+
26,KP Pietersen,226,226,432,1.0,0.0,262,24,2,86.25,1,0.0,1.0,200+
27,IJL Trott,226,226,490,1.0,0.0,349,20,0,64.75,1,0.0,1.0,200+
28,RWT Key,221,221,426,1.0,0.0,288,31,0,76.73,1,0.0,1.0,200+
29,WJ Edrich,219,219,460,1.0,0.0,-,25,0,-,4,0.0,1.0,200+
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
94409,TJ Murtagh,5*,5,9,1.0,1.0,3,1,0,166.66,3,0.0,0.0,0-49
94410,TJ Murtagh,5,5,18,1.0,0.0,7,1,0,71.42,2,0.0,0.0,0-49
94411,A Balbirnie,5,5,16,1.0,0.0,10,1,0,50.00,4,0.0,0.0,0-49
94412,EC Joyce,4,4,9,1.0,0.0,4,0,0,100.00,2,0.0,0.0,0-49
94413,A Balbirnie,4,4,-,1.0,0.0,7,1,0,57.14,1,0.0,0.0,0-49
94414,JA McCollum,4,4,-,1.0,0.0,9,1,0,44.44,1,0.0,0.0,0-49
94415,AR McBrine,4,4,-,1.0,0.0,13,1,0,30.76,3,0.0,0.0,0-49
94416,KJ O'Brien,4,4,21,1.0,0.0,8,1,0,50.00,4,0.0,0.0,0-49
94417,SR Thompson,4,4,24,1.0,0.0,9,1,0,44.44,4,0.0,0.0,0-49
94418,SR Thompson,3,3,40,1.0,0.0,21,0,0,14.28,2,0.0,0.0,0-49
94419,SR Thompson,3,3,-,1.0,0.0,31,0,0,9.67,1,0.0,0.0,0-49
94420,AR McBrine,3,3,-,1.0,0.0,26,0,0,11.53,1,0.0,0.0,0-49
94421,MR Adair,3,3,22,1.0,0.0,9,0,0,33.33,2,0.0,0.0,0-49
94422,WTS Porterfield,2,2,23,1.0,0.0,19,0,0,10.52,4,0.0,0.0,0-49
94423,TJ Murtagh,2,2,12,1.0,0.0,5,0,0,40.00,4,0.0,0.0,0-49
94424,WTS Porterfield,1,1,30,1.0,0.0,20,0,0,5.00,2,0.0,0.0,0-49
94425,SW Poynter,1,1,-,1.0,0.0,9,0,0,11.11,3,0.0,0.0,0-49
94426,SR Thompson,1,1,-,1.0,0.0,12,0,0,8.33,3,0.0,0.0,0-49
94427,WB Rankin,0*,0,8,1.0,1.0,5,0,0,0.00,4,0.0,0.0,0-49
94428,A Balbirnie,0,0,16,1.0,0.0,8,0,0,0.00,2,0.0,0.0,0-49
94429,NJ O'Brien,0,0,12,1.0,0.0,10,0,0,0.00,2,0.0,0.0,0-49
94430,TE Kane,0,0,2,1.0,0.0,2,0,0,0.00,2,0.0,0.0,0-49
94431,A Balbirnie,0,0,5,1.0,0.0,4,0,0,0.00,3,0.0,0.0,0-49
94432,SW Poynter,0,0,-,1.0,0.0,2,0,0,0.00,1,0.0,0.0,0-49
94433,WTS Porterfield,0,0,-,1.0,0.0,2,0,0,0.00,3,0.0,0.0,0-49
94434,GC Wilson,0,0,4,1.0,0.0,4,0,0,0.00,2,0.0,0.0,0-49
94435,SR Thompson,0,0,12,1.0,0.0,5,0,0,0.00,2,0.0,0.0,0-49
94436,PR Stirling,0,0,4,1.0,0.0,2,0,0,0.00,4,0.0,0.0,0-49
94437,GC Wilson,0,0,4,1.0,0.0,2,0,0,0.00,4,0.0,0.0,0-49
94438,AR McBrine,0,0,10,1.0,0.0,2,0,0,0.00,4,0.0,0.0,0-49

# 100's
Possible values:
* 1: 99 < `Innings Runs Scored Num
* 0: Not a century
* NaN: For bowler rows

**Use**: No. Computed field

# Innings Runs Scored Buckets
Possible values:
* 200+
* 150-199
* 100-149
* 50-99
* 0-49

In [39]:
df['Innings Runs Scored Buckets'].unique()

array(['200+', '150-199', '100-149', '50-99', '0-49', '-', nan],
      dtype=object)